import createClient from "openapi-fetch";
import type { paths } from "../types/schema"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "api/" });
export default client;
