import createClient, {Middleware} from "openapi-fetch";
import type {paths} from "./schema"; // generated by openapi-typescript
export class ApiError extends Error {
    constructor(message: string,) {
        super(message);
        this.name = "ApiError";
    }
}

const myMiddleware: Middleware = {
    async onRequest({request}) {
        return request;
    },
    async onResponse({response}) {
        if (!response.ok) {
            const responseBody = await response.json();
            throw new ApiError(responseBody.title);
        }
        return response;
    },
};

const client = createClient<paths>();

// register middleware
client.use(myMiddleware);

export default client;